/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedChatRouteImport } from './routes/_authed.chat'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedFailoverRouteImport } from './routes/_authed.failover'
import { Route as AuthedInspectorRouteImport } from './routes/_authed.inspector'
import { Route as AuthedMemoryRouteImport } from './routes/_authed.memory'
import { Route as AuthedRecurrenceRouteImport } from './routes/_authed.recurrence'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedIncidentsIndexRouteImport } from './routes/_authed.incidents.index'
import { Route as AuthedIncidentsIdRouteImport } from './routes/_authed.incidents.$id'

const AuthedChatRoute = AuthedChatRouteImport.update({
  id: '/_authed/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/_authed/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedFailoverRoute = AuthedFailoverRouteImport.update({
  id: '/_authed/failover',
  path: '/failover',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedInspectorRoute = AuthedInspectorRouteImport.update({
  id: '/_authed/inspector',
  path: '/inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMemoryRoute = AuthedMemoryRouteImport.update({
  id: '/_authed/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRecurrenceRoute = AuthedRecurrenceRouteImport.update({
  id: '/_authed/recurrence',
  path: '/recurrence',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/_authed/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIncidentsIndexRoute = AuthedIncidentsIndexRouteImport.update({
  id: '/_authed/incidents/',
  path: '/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIncidentsIdRoute = AuthedIncidentsIdRouteImport.update({
  id: '/_authed/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/chat': typeof AuthedChatRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/failover': typeof AuthedFailoverRoute
  '/inspector': typeof AuthedInspectorRoute
  '/memory': typeof AuthedMemoryRoute
  '/recurrence': typeof AuthedRecurrenceRoute
  '/settings': typeof AuthedSettingsRoute
  '/incidents/$id': typeof AuthedIncidentsIdRoute
  '/incidents/': typeof AuthedIncidentsIndexRoute
}
export interface FileRoutesByTo {
  '/chat': typeof AuthedChatRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/failover': typeof AuthedFailoverRoute
  '/inspector': typeof AuthedInspectorRoute
  '/memory': typeof AuthedMemoryRoute
  '/recurrence': typeof AuthedRecurrenceRoute
  '/settings': typeof AuthedSettingsRoute
  '/incidents/$id': typeof AuthedIncidentsIdRoute
  '/incidents': typeof AuthedIncidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed/chat': typeof AuthedChatRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/failover': typeof AuthedFailoverRoute
  '/_authed/inspector': typeof AuthedInspectorRoute
  '/_authed/memory': typeof AuthedMemoryRoute
  '/_authed/recurrence': typeof AuthedRecurrenceRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/incidents/$id': typeof AuthedIncidentsIdRoute
  '/_authed/incidents/': typeof AuthedIncidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/chat'
    | '/dashboard'
    | '/failover'
    | '/inspector'
    | '/memory'
    | '/recurrence'
    | '/settings'
    | '/incidents/$id'
    | '/incidents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chat'
    | '/dashboard'
    | '/failover'
    | '/inspector'
    | '/memory'
    | '/recurrence'
    | '/settings'
    | '/incidents/$id'
    | '/incidents'
  id:
    | '__root__'
    | '/_authed/chat'
    | '/_authed/dashboard'
    | '/_authed/failover'
    | '/_authed/inspector'
    | '/_authed/memory'
    | '/_authed/recurrence'
    | '/_authed/settings'
    | '/_authed/incidents/$id'
    | '/_authed/incidents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedChatRoute: typeof AuthedChatRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedFailoverRoute: typeof AuthedFailoverRoute
  AuthedInspectorRoute: typeof AuthedInspectorRoute
  AuthedMemoryRoute: typeof AuthedMemoryRoute
  AuthedRecurrenceRoute: typeof AuthedRecurrenceRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIncidentsIdRoute: typeof AuthedIncidentsIdRoute
  AuthedIncidentsIndexRoute: typeof AuthedIncidentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed/chat': {
      id: '/_authed/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthedChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/failover': {
      id: '/_authed/failover'
      path: '/failover'
      fullPath: '/failover'
      preLoaderRoute: typeof AuthedFailoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/inspector': {
      id: '/_authed/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof AuthedInspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/memory': {
      id: '/_authed/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthedMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/recurrence': {
      id: '/_authed/recurrence'
      path: '/recurrence'
      fullPath: '/recurrence'
      preLoaderRoute: typeof AuthedRecurrenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/incidents/': {
      id: '/_authed/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof AuthedIncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/incidents/$id': {
      id: '/_authed/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof AuthedIncidentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthedChatRoute: AuthedChatRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedFailoverRoute: AuthedFailoverRoute,
  AuthedInspectorRoute: AuthedInspectorRoute,
  AuthedMemoryRoute: AuthedMemoryRoute,
  AuthedRecurrenceRoute: AuthedRecurrenceRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIncidentsIdRoute: AuthedIncidentsIdRoute,
  AuthedIncidentsIndexRoute: AuthedIncidentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
